### ISSUE TITLE
Importing segment 16_5.xml.gz.mp3 from segments/city/narrow leads to an interrupted import and error

### ISSUE THREAD

**Issue by tm67602** [Shatter-Team/Shatter#28]
When trying to import a vanilla Smash Hit segment (`16_5`) from Room 3 (`narrow`) of Checkpoint 11 (`city`), it is mostly able to load in, but some parts end up missing and it throws this error: 
![16_5 narrow error](https://github.com/Shatter-Team/Shatter/assets/100551859/c7e7215e-df38-4713-9585-06f5db8e331a)
I wasn't sure if the problem was on my end because everytime I tried to re-import it (even from other APKs), the same error kept popping up no matter what I did.

Below is the final result of the import, where large parts of the segment appear to be missing. What is weird about this is that none of the other Room 3 segments had the same problem as they were all able to be imported without issues.
![failedload](https://github.com/Shatter-Team/Shatter/assets/100551859/e4634724-edd5-4c95-9d02-becf5f6eca14)

Other Info: I am using Blender 3.6.5 LTS and Shatter 2023.11.8, both of which are the latest versions.

**Comment by knot126** [comment]
Thanks for the well written bug report! I'll look into this really soon, it should be fixed within the next day or two. 👍

**Comment by knot126** [comment]
Okay, I looked into this. It seems like the developers set one of the difficulty properties of an object to just be a blank string, for example:

```xml
<obstacle pos="0 0 0" type="sweeper" difficulty=" " />
```

Which Shatter was not prepared to handle, since if the property exists it expects two values for the difficulty property.

I believe the SH official level editor had the user edit the strings in the XML file directly, so it's possible it ended up like this as a mistake where one of the developers accidently added a space to the feild without realising it, and Smash Hit never complained about it so it stayed.

Anyway, it's fixed in a development build now. I'm going to release another update soon so it will be bundled with that.

**Comment by knot126** [comment]
This is fixed in 2023.11.11.
